services:
  postgres:
    image: postgres:16.2
    environment:
      POSTGRES_DB: "gophkeeper"
      POSTGRES_USER: "gophkeeper"
      POSTGRES_PASSWORD: "gophkeeper"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
