name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.1'

    - name: Build
      run: go build -v ./...

  linter:
    runs-on: ubuntu-latest
    steps:
      - name: GolangCI-Linter
        uses: Mushus/golangci-linter@v1.1.2
      
  test:
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:27.2.1-dind-rootless
        ports:
          - 2375:2375
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.1'

    - name: Test with Docker
      run: go test -v ./...
          
