name: Go

on:
  release:
    types:
      - published
      - edited

permissions:
    contents: write
    packages: write

jobs:
  releases:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: ["386", amd64, arm64]
        exclude:
          - goarch: "386"
            goos: darwin
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v4
    - name: compile and release 
      uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        goversion: "https://go.dev/dl/go1.23.1.linux-amd64.tar.gz"
        project_path: "./cmd/client"
        binary_name: "client"
        extra_files: README.md
